# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - id: darwin
    binary: '{{ .ProjectName }}-{{ .Env.VERSION }}{{ if .IsSnapshot}}-SNAPSHOT{{ end }}-{{ .Os }}-{{ if eq .Arch "amd64" }}x86_64{{ end }}{{ if eq .Arch "arm64" }}aarch64{{ end }}/{{ .ProjectName }}'
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    no_unique_dist_dir: true
  - id: linux
    binary: '{{ .ProjectName }}-{{ .Env.VERSION }}{{ if .IsSnapshot}}-SNAPSHOT{{ end }}-{{ .Os }}-{{ if eq .Arch "amd64" }}x86_64{{ end }}{{ if eq .Arch "386" }}x86{{ end }}{{ if eq .Arch "arm64" }}{{ .Arch }}{{ end }}/{{ .ProjectName }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - 386
    no_unique_dist_dir: true
  - id: windows
    binary: '{{ .ProjectName }}-{{ .Env.VERSION }}{{ if .IsSnapshot}}-SNAPSHOT{{ end }}-{{ .Os }}-{{ if eq .Arch "amd64" }}x86_64{{ end }}{{ if eq .Arch "386" }}x86{{ end }}/{{ .ProjectName }}'
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
      - 386
    no_unique_dist_dir: true
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: x86_64
    format: gz
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dist: build/binaries
env:
  - VERSION=8.3.0